# Generated by Django 5.2.3 on 2025-06-29 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('thumbnail1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('thumbnail2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('thumbnail3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('thumbnail4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('thumbnail5', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('color_options', models.JSONField(default=list)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='backend.category')),
            ],
        ),
    ]
