# Generated by Django 5.2.3 on 2025-07-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_colorvariant_colorvariantimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorvariantimage',
            name='color_variant',
        ),
        migrations.DeleteModel(
            name='ColorVariant',
        ),
        migrations.DeleteModel(
            name='ColorVariantImage',
        ),
    ]
