# Generated by Django 5.2.3 on 2025-07-13 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('main_image', models.ImageField(upload_to='products/colors/')),
                ('thumbnail1', models.ImageField(blank=True, null=True, upload_to='products/colors/')),
                ('thumbnail2', models.ImageField(blank=True, null=True, upload_to='products/colors/')),
                ('thumbnail3', models.ImageField(blank=True, null=True, upload_to='products/colors/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='backend.product')),
            ],
        ),
    ]
