# Generated by Django 5.2.3 on 2025-07-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_colorvariant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColorVariant',
        ),
    ]
