# Generated by Django 5.2.3 on 2025-07-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_productcolorimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_options',
        ),
    ]
