# Generated by Django 5.2.3 on 2025-07-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_product_color_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_options',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='ProductColorImage',
        ),
    ]
